spring:
  application:
    name: libmanager
  datasource:
    url: jdbc:mysql://localhost:3306/library_manage1
    username: root
    password: 141203
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ntluanb22352003@gmail.com
    password: xcfjgiucrogcjogw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    serialization.write-dates-as-timestamps: false
  liquibase:
    enabled: false
    # change-log: classpath:db/changelog/db.changelog-master.xml
  spring:
    data:
      mongodb:
        uri: mongodb://localhost:27017/lib_manager
        database: lib_manager

server:
  port: 8080

app:
  support-email: libmanage.support@gmail.com
  maintenance-mode: false
  verify-email-url: http://localhost:5173/verify-otp/
  reset-password-url: http://localhost:5173/reset-password/

jwt:
  signing.key: yGIVSMe9sP0iJDJMpSIph503ZM1uhQlfiPVjp/Hi1Yyv6Nd0kbwQ6omdwcAgA7xt
  valid-duration: 3600
  refresh-duration: 2592000
  reset-duration: 3600

security:
  public-endpoints-post: /auth/**,/account/**,/password/**,/swagger-ui/**,/v3/api-docs/**,/v3/api-docs,/swagger-resources/**,/webjars/**,/v3/api-docs.yaml,/assets/**,/favicon.ico,/books/search
  public-endpoints-get: /auth/verify-email,/swagger-ui/**,/v3/api-docs/**,/v3/api-docs,/swagger-resources/**,/webjars/**,/v3/api-docs.yaml,/assets/**,/favicon.ico,/books/all,/books/detail,/chat/**
  permissions:
    admin_role: /admin/**
    user_role: /user/**

cloudinary:
  url: cloudinary://889665562338234:0Rwrk8DO16E62EIs7Bz_c6u0fNg@ddvgzy4xh
  folder: books
  max_file_size: 5242880
  allowed_extensions: jpg,jpeg,png,gif

springdoc:
  show-spring-exceptions: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html